---
  - block:
    - name: Clone AMZN EFS utils repository
      git:
        repo: 'https://github.com/aws/efs-utils'
        dest: '/tmp/efs-utils'
        clone: yes
        force: yes

    - name: Build amazon-efs-utils .deb package
      shell: './build-deb.sh'
      args:
        chdir: '/tmp/efs-utils'

    - name: Install amazon-efs-utils
      shell: 'apt-get -y install ./build/amazon-efs-utils*deb'
      args:
        chdir: '/tmp/efs-utils'

    become: true