---
  - name: Install required APT packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: present
      autoclean: yes
      autoremove: yes
    vars:
      packages:
        - make
        - binutils